# Generated by Django 3.1.2 on 2021-09-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210910_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hike',
            name='img_one',
            field=models.CharField(default='https://source.unsplash.com/Bkci_8qcdvQ', max_length=500),
        ),
        migrations.AlterField(
            model_name='hike',
            name='img_three',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='hike',
            name='img_two',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
